#!/bin/bash

pip_installed() {
  command -v pip >/dev/null 2>&1

  if [ $? -eq 0 ]; then
      echo "pip is installed."
  else
      echo "pip is not installed, proceeding to installation..."
      python -m ensurepip --upgrade
  fi
}

module_installed() {
  # name of the module, required for installation
  module=$1

  # import <module> in python code
  import=$2

  # checking whether import is any different than module
  if [ -z "$2" ]; then
    import=$module
  fi

  python -c "import ${import}" >/dev/null 2>&1

  # checking if the last command returned 0, if so then installed
  if [ $? -eq 0 ]; then
        echo "${module} is installed, skipping the installation."
  else
      echo "${module} is not installed, proceeding to installation..."
      pip install ${module}
  fi
}

# required modules
pip_installed
module_installed pyinstaller PyInstaller
module_installed xmltodict
module_installed pyyaml yaml
